// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "RoofMaster Support",
            "url": "https://example.com",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/roof_angle_calculation": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список заявок пользователя с опциональной фильтрацией по статусу и датам.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roof angle calculations"
                ],
                "summary": "Список заявок пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Фильтр по статусу",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Дата от (YYYY-MM-DD)",
                        "name": "from-date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Дата до (YYYY-MM-DD)",
                        "name": "to-date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AngleCalculationListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/roof_angle_calculation/current_tilt_calculation": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает ID draft-заявки и количество материалов в ней.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roof angle calculations"
                ],
                "summary": "Информация о текущей draft-заявке",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.DraftRoofAngleCalculationInfo"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/roof_angle_calculation/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает заявку и список материалов в ней.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roof angle calculations"
                ],
                "summary": "Детальная информация о заявке",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AngleCalculationDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет параметры заявки (снеговая и ветровая нагрузки).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roof angle calculations"
                ],
                "summary": "Обновить заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Параметры заявки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AngleCalculationUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AngleCalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет заявку пользователя (меняет статус на deleted).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roof angle calculations"
                ],
                "summary": "Удалить заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/roof_angle_calculation/{id}/finish": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Устанавливает статус заявки completed или rejected (только для модератора).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roof angle calculations"
                ],
                "summary": "Завершить или отклонить заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый статус заявки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AngleCalculationFinishRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AngleCalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/roof_angle_calculation/{id}/form": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Переводит draft-заявку в статус formed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roof angle calculations"
                ],
                "summary": "Сформировать заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AngleCalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/roof_angle_calculation/{id}/{material_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет толщину материала в draft-заявке.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roof angle calculations"
                ],
                "summary": "Обновить толщину материала",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID материала",
                        "name": "material_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новая толщина",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.MaterialThicknessUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.RoofingMaterialInCalculation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет материал из draft-заявки.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roof angle calculations"
                ],
                "summary": "Удалить материал из заявки",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID материала",
                        "name": "material_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AngleCalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/roofing_materials": {
            "get": {
                "description": "Возвращает список всех кровельных материалов с опциональным поиском по названию.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roofing materials"
                ],
                "summary": "Список кровельных материалов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поиск по названию материала",
                        "name": "roofing_material",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.RoofingMaterialsListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает новый кровельный материал (только для администратора).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roofing materials"
                ],
                "summary": "Создать кровельный материал",
                "parameters": [
                    {
                        "description": "Данные материала",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RoofingMaterialRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.RoofingMaterialDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/roofing_materials/{id}": {
            "get": {
                "description": "Возвращает кровельный материал по идентификатору.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roofing materials"
                ],
                "summary": "Материал по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID материала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.RoofingMaterialDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет существующий кровельный материал (только для администратора).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roofing materials"
                ],
                "summary": "Обновить кровельный материал",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID материала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные материала",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RoofingMaterialRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.RoofingMaterialDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Помечает материал как удаленный (только для администратора).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roofing materials"
                ],
                "summary": "Удалить кровельный материал",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID материала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/roofing_materials/{id}/photo": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Загружает фото для материала в MinIO и обновляет URL (только для администратора).",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roofing materials"
                ],
                "summary": "Загрузить фото материала",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID материала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Файл изображения",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.RoofingMaterialDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/roofing_materials/{id}/roof_angle_calculation": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавляет материал в текущую draft-заявку пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roofing materials"
                ],
                "summary": "Добавить материал в заявку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID материала",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AngleCalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает данные текущего авторизованного пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Информация о текущем пользователе",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет логин и/или пароль текущего пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Обновление данных пользователя",
                "parameters": [
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UserUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Аутентифицирует пользователя и возвращает пару access/refresh токенов.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход пользователя",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Отзывает access токен (blacklist в Redis) и опционально refresh токен.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход пользователя",
                "parameters": [
                    {
                        "description": "Токены для выхода",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Создает нового пользователя с логином и паролем.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AngleCalculationDetailResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "description": "Время завершения заявки",
                    "type": "string"
                },
                "created_at": {
                    "description": "Дата создания заявки",
                    "type": "string"
                },
                "creator_id": {
                    "description": "ID создателя заявки",
                    "type": "integer"
                },
                "formed_at": {
                    "description": "Время формирования заявки",
                    "type": "string"
                },
                "moderator_id": {
                    "description": "ID модератора (если назначен)",
                    "type": "integer"
                },
                "roofing_material_count": {
                    "description": "Количество материалов в заявке",
                    "type": "integer"
                },
                "roofing_materials": {
                    "description": "Материалы в заявке",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.RoofingMaterialInCalculation"
                    }
                },
                "snow_load": {
                    "description": "Снеговая нагрузка",
                    "type": "integer"
                },
                "status": {
                    "description": "Статус заявки",
                    "type": "string"
                },
                "tilt_angle_calculation_id": {
                    "description": "ID заявки",
                    "type": "integer"
                },
                "wind_load": {
                    "description": "Ветровая нагрузка",
                    "type": "integer"
                }
            }
        },
        "domain.AngleCalculationFinishRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "description": "Новый статус: \"completed\" или \"rejected\"",
                    "type": "string"
                }
            }
        },
        "domain.AngleCalculationListResponse": {
            "type": "object",
            "properties": {
                "tilt_angle_calculation_count": {
                    "description": "Общее количество заявок",
                    "type": "integer"
                },
                "tilt_angle_calculations": {
                    "description": "Массив заявок",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.AngleCalculationResponse"
                    }
                }
            }
        },
        "domain.AngleCalculationResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "description": "Время завершения заявки",
                    "type": "string"
                },
                "created_at": {
                    "description": "Дата создания заявки",
                    "type": "string"
                },
                "creator_id": {
                    "description": "ID создателя заявки",
                    "type": "integer"
                },
                "formed_at": {
                    "description": "Время формирования заявки",
                    "type": "string"
                },
                "moderator_id": {
                    "description": "ID модератора (если назначен)",
                    "type": "integer"
                },
                "roofing_material_count": {
                    "description": "Количество материалов в заявке",
                    "type": "integer"
                },
                "snow_load": {
                    "description": "Снеговая нагрузка",
                    "type": "integer"
                },
                "status": {
                    "description": "Статус заявки",
                    "type": "string"
                },
                "tilt_angle_calculation_id": {
                    "description": "ID заявки",
                    "type": "integer"
                },
                "wind_load": {
                    "description": "Ветровая нагрузка",
                    "type": "integer"
                }
            }
        },
        "domain.AngleCalculationUpdateRequest": {
            "type": "object",
            "properties": {
                "snow_load": {
                    "description": "Новое значение снеговой нагрузки",
                    "type": "integer"
                },
                "wind_load": {
                    "description": "Новое значение ветровой нагрузки",
                    "type": "integer"
                }
            }
        },
        "domain.DraftRoofAngleCalculationInfo": {
            "type": "object",
            "properties": {
                "roofing_materials_count": {
                    "type": "integer"
                },
                "tilt_angle_calculation_id": {
                    "description": "-1 если нет draft заявки",
                    "type": "integer"
                }
            }
        },
        "domain.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "Краткоживущий access-токен (JWT)",
                    "type": "string"
                },
                "expires_in": {
                    "description": "Время жизни access-токена в секундах",
                    "type": "integer"
                },
                "is_moderator": {
                    "description": "Признак модератора (администратора)",
                    "type": "boolean"
                },
                "login": {
                    "description": "Логин пользователя",
                    "type": "string"
                },
                "refresh_token": {
                    "description": "Долгоживущий refresh-токен",
                    "type": "string"
                },
                "user_id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer"
                }
            }
        },
        "domain.LogoutRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "description": "Опциональный refresh-токен для отзыва",
                    "type": "string"
                }
            }
        },
        "domain.MaterialThicknessUpdateRequest": {
            "type": "object",
            "properties": {
                "thickness": {
                    "description": "Новое значение толщины (мм)",
                    "type": "integer"
                }
            }
        },
        "domain.RoofingMaterialDetailResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Описание материала",
                    "type": "string"
                },
                "is_delete": {
                    "description": "Пометка, что материал удалён (soft delete)",
                    "type": "boolean"
                },
                "max_tilt_angle": {
                    "description": "Максимально допустимый угол наклона",
                    "type": "integer"
                },
                "min_tilt_angle": {
                    "description": "Минимально допустимый угол наклона",
                    "type": "integer"
                },
                "photo": {
                    "description": "URL фотографии материала",
                    "type": "string"
                },
                "roofing_material_id": {
                    "description": "Идентификатор материала",
                    "type": "integer"
                },
                "title": {
                    "description": "Название материала",
                    "type": "string"
                },
                "video_url": {
                    "description": "URL видео материала (MinIO)",
                    "type": "string"
                }
            }
        },
        "domain.RoofingMaterialInCalculation": {
            "type": "object",
            "properties": {
                "is_delete": {
                    "description": "Пометка, что материал удалён (soft delete)",
                    "type": "boolean"
                },
                "max_tilt_angle": {
                    "description": "Максимально допустимый угол наклона",
                    "type": "integer"
                },
                "min_tilt_angle": {
                    "description": "Минимально допустимый угол наклона",
                    "type": "integer"
                },
                "optimal_tilt_angle": {
                    "description": "Рассчитанный оптимальный угол наклона (для completed)",
                    "type": "integer"
                },
                "photo": {
                    "description": "URL фотографии материала",
                    "type": "string"
                },
                "roofing_material_id": {
                    "description": "Идентификатор материала",
                    "type": "integer"
                },
                "thickness": {
                    "description": "Выбранная толщина материала (если задана)",
                    "type": "integer"
                },
                "title": {
                    "description": "Название материала",
                    "type": "string"
                }
            }
        },
        "domain.RoofingMaterialRequest": {
            "type": "object",
            "required": [
                "max_tilt_angle",
                "min_tilt_angle",
                "title"
            ],
            "properties": {
                "description": {
                    "description": "Описание материала",
                    "type": "string"
                },
                "max_tilt_angle": {
                    "description": "Максимальный угол наклона",
                    "type": "integer"
                },
                "min_tilt_angle": {
                    "description": "Минимальный угол наклона",
                    "type": "integer"
                },
                "title": {
                    "description": "Название материала",
                    "type": "string"
                }
            }
        },
        "domain.RoofingMaterialResponse": {
            "type": "object",
            "properties": {
                "is_delete": {
                    "description": "Пометка, что материал удалён (soft delete)",
                    "type": "boolean"
                },
                "max_tilt_angle": {
                    "description": "Максимально допустимый угол наклона",
                    "type": "integer"
                },
                "min_tilt_angle": {
                    "description": "Минимально допустимый угол наклона",
                    "type": "integer"
                },
                "photo": {
                    "description": "URL фотографии материала",
                    "type": "string"
                },
                "roofing_material_id": {
                    "description": "Идентификатор материала",
                    "type": "integer"
                },
                "title": {
                    "description": "Название материала",
                    "type": "string"
                }
            }
        },
        "domain.RoofingMaterialsListResponse": {
            "type": "object",
            "properties": {
                "roofing_materials": {
                    "description": "Массив материалов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.RoofingMaterialResponse"
                    }
                }
            }
        },
        "domain.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Статус операции (\"success\" и т.п.)",
                    "type": "string"
                }
            }
        },
        "domain.UserLoginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "description": "Логин пользователя",
                    "type": "string"
                },
                "password": {
                    "description": "Пароль пользователя",
                    "type": "string"
                }
            }
        },
        "domain.UserRegisterRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "description": "Логин пользователя",
                    "type": "string"
                },
                "password": {
                    "description": "Пароль пользователя",
                    "type": "string"
                }
            }
        },
        "domain.UserResponse": {
            "type": "object",
            "properties": {
                "is_moderator": {
                    "description": "Является ли пользователь модератором",
                    "type": "boolean"
                },
                "login": {
                    "description": "Логин пользователя",
                    "type": "string"
                },
                "user_id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer"
                }
            }
        },
        "domain.UserUpdateRequest": {
            "type": "object",
            "properties": {
                "login": {
                    "description": "Новый логин (опционально)",
                    "type": "string"
                },
                "password": {
                    "description": "Новый пароль (опционально)",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "RoofMaster API",
	Description:      "API для расчета оптимального угла наклона кровли, управления кровельными материалами и заявками.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
